/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401.h"
#include"gpio.h"
#include "otg.h"
#include"timer.h"
OTG_FS_ConFig_t g;
uint32_t packet[64];
USB_SETUP_PACKET op,pp;
uint8_t mode,pktsts=0,count=0,count1=0,key=0;
uint16_t bcnt=0,addr,addr1;
char bufer[11];
uint8_t set_line[7];
uint8_t receive[64];


TIM_Handle_t tim1,tim2;
//uint8_t data_line=0,data_right=0;
int8_t data_left=0,real1=0,data_left1=0,data_left_last=0;
int16_t et_pre1=0,et_pre2=0;
int16_t derivative=0;
int16_t real=0,kq=0;
uint16_t dem1=0,dem2=0,d=0,dem4=0;
int16_t en_left=0,en_right=0,en1_left=0,en1_right=0;
uint8_t tl=0,tr=0,prior=0,prior1=0,prior2=0,a=0,b=0,flag=0,testcase=0,modem=0,c=0,flag1=0,flag2=0,flag3=0;
int integral=0,dem3=0,dem=0;
////////////////////////////
int intergral2=0,et_pre3=0,derivative1=0,pwm_mm2=0,intergral3=0,et_pre4=0,derivative2=0,pwm_mm1=0,count_left=0,count_right=0;
//
char colo;
void line_init()
{
	GPIO_Handle_t y;
	//5 line trong
	y.gpiox=GPIOA;
	y.gpioy.mode= GPIO_INPUT;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.speed=GPIO_VR_HIGH_SPEED;
	y.gpioy.alt_function=GPIO_PIN_AF0;
	y.gpioy.pupd=GPIO_PD;
	y.gpioy.gpio_pin=GPIO_PIN_1;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_2;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_3;
	GPIO_Init(&y);
	//mode side
	y.gpiox=GPIOB;
	y.gpioy.gpio_pin=GPIO_PIN_4;
	GPIO_Init(&y);
	//chan pwm
	y.gpiox=GPIOA;
	y.gpioy.mode= GPIO_OUTPUT;
	y.gpioy.gpio_pin=GPIO_PIN_7;
	GPIO_Init(&y);

	y.gpiox=GPIOB;
	y.gpioy.mode= GPIO_OUTPUT;
	y.gpioy.gpio_pin=GPIO_PIN_0;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_1;
	GPIO_Init(&y);
//line 2 ben
	y.gpiox=GPIOA;
	y.gpioy.mode=GPIO_IRQ_RTFT;
	y.gpioy.gpio_pin=GPIO_PIN_5;
	y.gpioy.pupd=GPIO_PU ;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_6;
	GPIO_Init(&y);
	NVIC_IRQ_ConFig(23,ENABLE);
	NVIC_IRQ_PriorityConFig(23,1);

	y.gpiox=GPIOA;
	y.gpioy.mode=GPIO_IRQ_RTFT;
	y.gpioy.gpio_pin=GPIO_PIN_0;
	y.gpioy.pupd=GPIO_PD;
	GPIO_Init(&y);
	NVIC_IRQ_ConFig(6,ENABLE);
	NVIC_IRQ_PriorityConFig(6,1);
	y.gpiox=GPIOA;
	y.gpioy.mode=GPIO_IRQ_RTFT;
	y.gpioy.pupd=GPIO_PD;
	y.gpioy.gpio_pin=GPIO_PIN_4;
	GPIO_Init(&y);
	NVIC_IRQ_ConFig(10,ENABLE);
	NVIC_IRQ_PriorityConFig(10,1);

}
void encoder_init()
{
	GPIO_Handle_t y;
	y.gpiox=GPIOB;
	y.gpioy.mode=GPIO_IRQ_RTFT;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.speed=GPIO_VR_HIGH_SPEED;
	y.gpioy.alt_function=GPIO_PIN_AF0;
	y.gpioy.gpio_pin=GPIO_PIN_12;
	y.gpioy.pupd=GPIO_PU;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_15;
	GPIO_Init(&y);

	y.gpiox=GPIOA;
	y.gpioy.gpio_pin=GPIO_PIN_11;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_10;
	GPIO_Init(&y);
	NVIC_IRQ_ConFig(40,ENABLE);
	NVIC_IRQ_PriorityConFig(40,1);
}
void sonic_init()
{
	GPIO_Handle_t y;
	y.gpiox=GPIOA;
	y.gpioy.mode=GPIO_IRQ_RT;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.speed=GPIO_VR_HIGH_SPEED;
	y.gpioy.alt_function=GPIO_PIN_AF0;
	y.gpioy.gpio_pin=GPIO_PIN_8;
	y.gpioy.pupd=GPIO_PU;
	GPIO_Init(&y);
	y.gpioy.mode=GPIO_OUTPUT;
	y.gpioy.gpio_pin=GPIO_PIN_9;
	GPIO_Init(&y);
}
////////////////////-pid endcoder-///////////////////
int pid_encoder(int16_t speed,int16_t real_encoder,int*integra,int*derivativ,int16_t*et_pr)
{
	int kp=7500;
	int ki=130;
	int kd=2000;
	int et=speed-(real_encoder);
	//if(et==0) *integra=0;
	if(*integra>=1000) *integra=1000;
	else if(*integra<=-1000) *integra=-1000;
	*integra+=(et*5);
	 *derivativ=(et-*et_pr)/5;
	 int ut=(int)(kp*et +(ki*(*integra)) + (kd*( *derivativ)))/100;
	*et_pr=et;

	if(ut>=1000) ut=1000;
	else if(ut<-1000) ut=-1000;
	kq=ut;
	return ut;
}
int16_t pwm_left=0;
int16_t pwm_right=0;
int16_t  pid_caculate(uint8_t set_line,int8_t real_data,int*integral1,int16_t*derivative1,int16_t*et_pre,int kp,int ki,int kd)
{
/*	 int kp=95;
	 int ki=115;
	 int kd=0;*/


	 int16_t et=set_line-(real_data);
	// if(et>=-1 && et<=1)
	 if(kq>-1000 && kq<1000)
	 *integral1+=(et*5);
	 if(et==0)  *integral1=0;
	 if((*integral1>=20000)) *integral1=20000;else if((*integral1)<=-20000) *integral1=20000;
	 *derivative1=(et-*et_pre)/5;

	 if((*derivative1)>1000) *derivative1=1000 ;else if((*derivative1)<-1000) *derivative1=-1000;
	 int16_t ut=(int16_t)(kp*et +(ki*(*integral1))/1000 + (kd*( *derivative1)));
	 *et_pre=et;
	 kq=ut;

	return ut;
}

int8_t read_data_line()
{
	int8_t sensor[5], error;
	for(uint8_t i=1;i<6;i++)
	{
		sensor[i-1]=GPIO_ReadPin(GPIOA,i-1);
	}
	       if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==0)&&(sensor[3]==0)&&(sensor[4]==1)) error=4;

	  else if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==0)&&(sensor[3]==1)&&(sensor[4]==1)) error=3;

	  else if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==0)&&(sensor[3]==1)&&(sensor[4]==0)) error=2;

	  else if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==1)&&(sensor[3]==1)&&(sensor[4]==0)) error=1;
	 // else if((sensor[0]==1)&&(sensor[1]==1)&&(sensor[2]==1)&&(sensor[3]==0)&&(sensor[4]==0)) error=-3;


	  else if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==1)&&(sensor[3]==0)&&(sensor[4]==0)) error=0;

	  //else if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==1)&&(sensor[3]==1)&&(sensor[4]==1)) error=3;
	  else if((sensor[0]==0)&&(sensor[1]==1)&&(sensor[2]==1)&&(sensor[3]==0)&&(sensor[4]==0)) error=-1;

	  else if((sensor[0]==0)&&(sensor[1]==1)&&(sensor[2]==0)&&(sensor[3]==0)&&(sensor[4]==0)) error=-2;

	  else if((sensor[0]==1)&&(sensor[1]==1)&&(sensor[2]==0)&&(sensor[3]==0)&&(sensor[4]==0)) error=-3;

	  else if((sensor[0]==1)&&(sensor[1]==0)&&(sensor[2]==0)&&(sensor[3]==0)&&(sensor[4]==0)) error=-4;

	  else if((sensor[0]==0)&&(sensor[1]==0)&&(sensor[2]==0)&&(sensor[3]==0)&&(sensor[4]==0))
	  {
         error=7;
	  }
	  else  error=-7;
	  return error;

}
void TIM2_init()
{
	tim2.timx=TIM2;
	tim2.timy.mode=0;
	tim2.timy.ARR_control=TIM_ARR_DI;
	tim2.timy.DIR_control=TIM_UPCNT;
	tim2.timy.one_pulse=TIM_ONE_PULSE_DI;
	tim2.timy.psc=239; //1ms
	TIM_Init(&tim2);
}
void TIM2_PWM()
{
	TIM2->ARR=999;
	TIM2->CCMR[1]&=~(0x07<<4);
	TIM2->CCMR[0]&=~(0x07<<12);
	TIM2->CCMR[0]|=(0x06<<12);//pWM mode for channel 2
	TIM2->CCMR[1]|=(0x06<<4);//pWM mode for channel 3

	TIM2->CCMR[0]|=(1<<11);
	TIM2->CCMR[1]|=(1<<3);
	TIM2->CCER|=1<<8|1<<4;
	TIM2->CCR[2]=0;//ccr3
	TIM2->CCR[1]=0;//ccr2
	TIM2->CR1|=1<<7;
	TIM2->EGR|=1;

	TIM2->CR1|=1;
	GPIO_Handle_t y;
	y.gpiox=GPIOB;
	y.gpioy.mode=GPIO_ALT_FUNCTION;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.gpio_pin=GPIO_PIN_10;
	y.gpioy.speed=GPIO_VR_HIGH_SPEED;
	y.gpioy.alt_function=GPIO_PIN_AF1;
	GPIO_Init(&y);
	y.gpioy.gpio_pin=GPIO_PIN_3;
	GPIO_Init(&y);


}
void motor_control(int16_t pwm,uint8_t pin,uint32_t*addr_pin,uint32_t*addr_timer,uint16_t max_speed,uint8_t *cc)
{

	if(pwm>=0)
	{
		  *cc=0;
		  GPIO_WritePin(addr_pin,pin,RESET);
		  *addr_timer=(pwm);//ccr3+
	}
	else
	{
		*cc=1;
		GPIO_WritePin(addr_pin,pin,SET);
		//pwm_right=max_speed+pwm_right;
		*addr_timer=abs(max_speed+pwm);//ccr3
	}

}
void pid_control(int16_t real1,uint16_t offset,int16_t max_speed,int16_t max_speed1)
{
	pwm_left=offset-real1;
	pwm_right=offset+real1;
	int lp=pwm_left*45/1000;
	int lp1=pwm_right*45/1000;
	if(pwm_mm2>max_speed) pwm_mm2=max_speed;
	else if(pwm_mm2<(-max_speed1+offset))pwm_mm2=(-max_speed1+offset);
	 if((testcase==10||testcase==6) && data_left==7 && prior==0)
		 {
		  lp=lp+2;
		 //count_right=count_right-2;
		 }
	 /*else if(testcase>=17 && data_left==7 && prior==0)
	 {
		 lp1=lp1+1;
	 }*/
	pwm_mm2 =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
	motor_control(pwm_mm2,0,GPIOB,&(TIM2->CCR[2]),max_speed,&tl);

	pwm_mm1 =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
	if(pwm_mm1>max_speed) pwm_mm1=max_speed;
	else if(pwm_mm1<(-max_speed1+offset))pwm_mm1=(-max_speed1+offset);
	motor_control(pwm_mm1,1,GPIOB,&(TIM2->CCR[1]),max_speed,&tr);
}
void choose_side (int16_t*a,int16_t*b,char color,int16_t value1,int16_t value2)
{
	*a=value1;
	*b=value2;
    if(color=='r') //red
	{
		int16_t tmp=0;
		tmp=*a;
		*a=*b;
		*b=tmp;
	}
}
void control_case(int  test ,char color)
{
	switch(test)
	{
	case 1:
		/*pwm_left=400;//400
		pwm_right=400;*/
		if(dem<5000)
		{
		choose_side(&pwm_left,&pwm_right,color,450,450);
		int lp=pwm_left*45/1000;
		int pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		int lp1=pwm_right*45/1000;
		int pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,450,1000,90,100,0);
		}
		else
		{
			if((data_left<=1 && data_left>=-1) || data_left ==-7)
			{
			pid_handle(0,350,1000,90,100,0);
			}
			if(data_left==0) flag2=1;
		}
		break;
	case 2:
		/*pwm_left=600;//400
		pwm_right=-250;*/

		choose_side(&pwm_left,&pwm_right,color,250,100);
		int lp=pwm_left*45/1000;
		int pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		int lp1=pwm_right*45/1000;
		int pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		//if(data_left>=-1 && data_left<=1) flag2=1;
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		//if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		 /*if((data_left==-2 || data_left==2)) */flag2=1;
		//else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;

		break;
	case 3:
		/*pwm_left=-250;
		pwm_right=600;*/
		choose_side(&pwm_left,&pwm_right,color,0,250);
		 lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		 motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		 lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
//		/*if(data_left==-2 || data_left==2)*/ flag2=1;
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		else if((pwm_left==pwm_right) &&(data_left==-2 || data_left==2)) flag2=1;
		else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;
		break;
	case 4:
		if(flag==1)
		{
		/*pwm_left=400;
		pwm_right=0;*/
		if((GPIO_ReadPin(GPIOA,5)==1 || GPIO_ReadPin(GPIOA,6)==1))
			{
			intergral3=0;intergral2=0;
			 flag=2;
			}
		choose_side(&pwm_left,&pwm_right,color,800,0);
		int lp=pwm_left*45/1000;
		int16_t pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);
		int lp1=pwm_right*45/1000;
		int pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		}
		else if(flag==2)
		{
			/*pwm_left=400;
			pwm_right=400;*/
			if((data_left>=-2 && data_left<=2) && data_left!=-7)
			{
			flag=3;
			flag2=1;
			GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			}
			//choose_side(&pwm_left,&pwm_right,color,200,200);
			pwm_right=200;
			pwm_left=350;
			int lp=pwm_left*45/1000;
			int16_t pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			int lp1=pwm_right*45/1000;
			int pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			if(color=='r')
			motor_control(pwmy+200,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			else if(color=='b') motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			if(data_left>=-2 && data_left<=2)
			pid_handle(0,250,1000,90,100,0);
		}
		break;
	case 5:
		/*pwm_left=400;
		pwm_right=400;*/
		choose_side(&pwm_left,&pwm_right,color,250,250);
		 lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		 lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,150,1000,90,100,0);
		//if(data_left>=-1 && data_left<=1)
		 flag2=1;
		break;
	case 6:
		if(en1_left<300 && en1_right<300)
		{
			if(data_left_last<0)
			{
				pwm_right=300;
				pwm_left=350;
			}
			else if(data_left_last>0)
			{
				pwm_right=350;
				pwm_left=300;
			}
			else
			{
				pwm_right=400;
				pwm_left=400;
			}
			//choose_side(&pwm_left,&pwm_right,color,350,350);
			 lp=pwm_left*45/1000;
			 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			 lp1=pwm_right*45/1000;
			pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			//pid_handle(0,0,1000,90,100,0);
		}
		else if(en1_left>=300 || en1_right>=300)
		{
			 choose_side(&pwm_left,&pwm_right,color,0,0);
			 lp=(pwm_left)*45/1000;
			 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			 lp1=pwm_right*45/1000;
			pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			if(GPIO_ReadPin(GPIOA,GPIO_PIN_5)==1) data_left=-4;
			if(GPIO_ReadPin(GPIOA,GPIO_PIN_6)==1) data_left=4;
			pid_handle(0,0,1000,90,100,0);
			if(data_left>=-1 && data_left<=1)
			{
			prior=0;
			prior1=0;
			prior2=0;
			flag2=1;
			}
		}
		break;
	case 7:
		/*pwm_left=-250;
		pwm_right=600;*/
		choose_side(&pwm_left,&pwm_right,color,0,250);
		 lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		 lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
//		if(data_left>=-1 && data_left<=1)
//		pid_handle(0,150,1000,90,100,0);
//		if(data_left==-2 || data_left==2) flag2=1;
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		else if((pwm_left==pwm_right) &&(data_left==-2 || data_left==2)) flag2=1;
		else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;
		break;
	case 8:
		/*pwm_left=400;
		pwm_right=400;*/
		choose_side(&pwm_left,&pwm_right,color,250,250);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,150,1000,90,100,0);
		 flag2=1;
		break;
	case 9:
		/*pwm_left=-250;
		pwm_right=600;*/
		choose_side(&pwm_left,&pwm_right,color,0,250);
		 lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		 lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		/*if(data_left>=-1 && data_left<=1)*/
		//pid_handle(0,150,1000,90,100,0);
		//data_left=read_data_line();
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		else if((pwm_left==pwm_right) &&(data_left==-2 || data_left==2)) flag2=1;
		else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;
		//pid_handle(0,150,1000,90,100,0);
		break;
	case 10:
		if(en1_left<=280 && en1_right<=280)
		{
			if(data_left_last<0)
			{
				pwm_right=300;
				pwm_left=350;
			}
			else if(data_left_last>0)
			{
				pwm_right=350;
				pwm_left=300;
			}
			else
			{
				pwm_right=400;
				pwm_left=400;
			}
			choose_side(&pwm_left,&pwm_right,color,320,320);
			 lp=pwm_left*45/1000;
			 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx+100,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			 lp1=pwm_right*45/1000;
			if(color=='r') lp1=lp1-2;else if(colo=='b') lp1=lp1+2;
			pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			//pid_handle(0,0,1000,90,100,0);
		}
		else if(en1_left>280 || en1_right>280)
		{
			 choose_side(&pwm_left,&pwm_right,color,0,0);
			 lp=(pwm_left)*45/1000;
			 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			 lp1=pwm_right*45/1000;
			pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			if(GPIO_ReadPin(GPIOA,GPIO_PIN_5)==1) data_left=-4;
			if(GPIO_ReadPin(GPIOA,GPIO_PIN_6)==1) data_left=4;
			pid_handle(0,0,1000,90,100,0);
			if(data_left>=-1 && data_left<=1)
			{
			prior=0;
			prior1=0;
			prior2=0;
			flag2=1;
			}
		}
		break;
	case 11:
		/*pwm_left=600;//400
		pwm_right=0;*/
		choose_side(&pwm_left,&pwm_right,color,250,100);
		 lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		 lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
//		if(data_left>=-1 && data_left<=1)
//		pid_handle(0,150,1000,90,100,0);
//		if(data_left==-2 || data_left==2) flag2=1;
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		else if((pwm_left==pwm_right) &&(data_left==-2 || data_left==2)) flag2=1;
		else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;
		break;
	case 12:
		/*pwm_left=400;//400
		pwm_right=400;*/
		choose_side(&pwm_left,&pwm_right,color,250,250);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,150,1000,90,100,0);
		//if(data_left==0)
		flag2=1;
		break;
	case 13:
		/*pwm_left=600;
		pwm_right=-250;*/
		choose_side(&pwm_left,&pwm_right,color,250,0);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
//		if(data_left>=-1 && data_left<=1)
//		pid_handle(0,150,1000,90,100,0);
//		if(data_left==-2 || data_left==2) flag2=1;
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		else if((pwm_left==pwm_right) &&(data_left==-2 || data_left==2)) flag2=1;
		else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;
		break;
	case 14:
		/*pwm_left=400;
		pwm_right=400;*/
		choose_side(&pwm_left,&pwm_right,color,250,250);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,150,1000,90,100,0);
		 flag2=1;
		break;
	case 15:
		/*pwm_left=400;
		pwm_right=400;*/
		choose_side(&pwm_left,&pwm_right,color,250,250);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,150,1000,90,100,0);
		 flag2=1;
		break;
	case 16:
		/*pwm_left=400;
		pwm_right=400;*/
		choose_side(&pwm_left,&pwm_right,color,250,250);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		pid_handle(0,150,1000,90,100,0);
		flag2=1;
		break;
	case 17:
		/*pwm_left=400;
		pwm_right=400;*/
		flag=0;
		choose_side(&pwm_left,&pwm_right,color,-50,250);
		lp=pwm_left*45/1000;
		 pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		/*if(data_left>=-1 && data_left<=1)
		pid_handle(0,150,1000,90,100,0);*/
	//	if(data_left==-2 || data_left==2) flag2=1;
		a=GPIO_ReadPin(GPIOA,5);
		b=GPIO_ReadPin(GPIOA,6);
		if(pwm_left>pwm_right &&data_left>=3 && a==0 && b==0) flag2=1;
		else if((pwm_left==pwm_right) &&(data_left==-2 || data_left==2)) flag2=1;
		else if((pwm_right>pwm_left) &&data_left<=-3&& a==0 && b==0 && data_left!=-7) flag2=1;
		break;
	case 18:
		int tmp;
		if(color=='b') tmp=en1_left;else if(color=='r') tmp=en1_right;
		if(tmp<300)
		{
		choose_side(&pwm_left,&pwm_right,color,150,0);
		lp=pwm_left*45/1000;
		pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		}
		else if(tmp>300)
		{
			choose_side(&pwm_left,&pwm_right,color,0,0);
			lp=pwm_left*45/1000;
			pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			lp1=pwm_right*45/1000;
			pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			en_left=0;en_right=0;
			//flag=0;
		    prior2=0;
			prior=0;
			prior1=0;
			flag=0;
			flag2=0;
			flag3=0;
		}
		//pid_handle(0,450,1000,90,100,0);
		break;
	case 19:
		if(color=='b') tmp=en1_right;else if(color=='r') tmp=en1_left;
		if(tmp<300)
		{
		choose_side(&pwm_left,&pwm_right,color,-50,150);
		lp=pwm_left*45/1000;
		pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		}
		else if(tmp>300)
		{
			choose_side(&pwm_left,&pwm_right,color,0,0);
			lp=pwm_left*45/1000;
			pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
			motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

			lp1=pwm_right*45/1000;
			pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
			motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
			en_left=0;en_right=0;
		    prior2=0;
			prior=0;
			prior1=0;
			flag=0;
			flag2=0;
			flag3=0;
		}
		break;
	default:
		choose_side(&pwm_left,&pwm_right,color,0,0);
		lp=pwm_left*45/1000;
		pwmx =pid_encoder(lp,count_left,&intergral2,&derivative1,&et_pre3);
		motor_control(pwmx,0,GPIOB,&(TIM2->CCR[2]),1000,&tl);

		lp1=pwm_right*45/1000;
		pwmy =pid_encoder(lp1,count_right,&intergral3,&derivative2,&et_pre4);
		motor_control(pwmy,1,GPIOB,&(TIM2->CCR[1]),1000,&tr);
		break;
	}
}
void pid_handle(int16_t offset1,int16_t offset2,int16_t max_speed,int kp,int ki,int kd)
{
	  if(data_left>=-4 && data_left<=4)
	  {
	  if(data_left<=-2 || data_left>=2)
		  {
		  real=pid_caculate(0,data_left,&integral,&derivative,&et_pre2,kp,ki,kd);
		  pid_control(real,offset1,max_speed,max_speed);
		  }
	  else
		  {
		  if(testcase==1 && colo=='r' && data_left<=-2) data_left=0;
		  if(testcase==1 && colo=='b' && data_left>=2) data_left=0;
		  real=pid_caculate(0,data_left,&integral,&derivative,&et_pre1,kp,ki,kd);

		   pid_control(real,offset2,max_speed,max_speed);
		  }
	  }
	  else if((data_left==7 && (testcase>=17 ||testcase==6 || testcase==10)))
	  {
		  if(testcase==10 || testcase==6)
		  pid_control(0,350,max_speed,max_speed);
		  else pid_control(0,120,max_speed,max_speed);
	  }
	  else if(data_left==-7&& testcase<=2)  pid_control(0,150,max_speed,max_speed);
}
void sys_handle(uint8_t mode1,char color)
{
    if(prior==0 && prior1==0)
	{
    	    if(d<375 &&(testcase==3||testcase==4) && flag==0)
    	     {
    	    	flag=1;
    	     	prior=1;
    	     	prior2=1;
    	     	testcase=4;
    	     }
    	    else if(d<315 && flag==0 && testcase>=17)
    	    {
    	    	flag=1;
    	     	prior=1;
    	     	prior1=1;
    	     	prior2=1;
    	     	en1_left=0;en1_right=0;
    	     	testcase++;
    	    }
    	    else if((testcase==5||testcase==9) && data_left==7 )
  		    {
    	     	prior=1;
    	     	prior1=1;
    	     	prior2=1;
    	     	testcase++;
    	       intergral3=0;intergral2=0;
    	     	en1_left=0;en1_right=0;

  		    }
    	if(mode1==0)
    	{
    	if(testcase==12) pid_handle(0,150,1000,140,110,0);
    	else if(testcase>=17) pid_handle(0,120,1000,95,110,0);
    	else pid_handle(0,350,1000,95,110,0);
    	}
	    else pid_handle(0,0,1000,95,110,0);
	}
	else
	{
		//if(testcase>1)
		control_case(testcase,color);
		{
		if((GPIO_ReadPin(GPIOA,GPIO_PIN_0)==1 )||(GPIO_ReadPin(GPIOA,GPIO_PIN_4)==1)||testcase==4 || testcase==2)
		{
		control_case(testcase,color);
		prior1=1;
		prior2=1;
		intergral3=0;intergral2=0;dem=0;
		if(testcase==4 &&/*(GPIO_ReadPin(GPIOA,GPIO_PIN_1)==1) */data_left>=-3 && data_left<=3 && flag==3)
		{
			pid_handle(0,150,1000,95,110,0);
			//GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			//if(data_left>=-2 && data_left<=2)
			{

				a=GPIO_ReadPin(GPIOA,5);
				b=GPIO_ReadPin(GPIOA,6);
				if(a==0 && b==0)
					{
					prior=0;
					prior1=0;
					 prior2=0;
					 //intergral3=0;intergral2=0;
					}
			}
		}
		if(testcase==2)
		{
			if(data_left>=-1 && data_left<=1 && flag2==1)
			{
			//if(prior==1 && data_left>=-4 && data_left<=4)
			{
			a=GPIO_ReadPin(GPIOA,5);
			b=GPIO_ReadPin(GPIOA,6);
			if(a==0 && b==0 && flag2==1)
				{
				    prior2=0;
					prior=0;
					prior1=0;
					flag2=0;
					flag3=0;
					//intergral3=0;intergral2=0;
				}
			}
			//prior2=0;
			}
		}
		}
		else if(prior1==1)
		{
		control_case(testcase,color);
		//pid_handle(0,0,1000,90,100,0);
		//if(testcase>1)
		//else
		{
			if(data_left<=1 && data_left>=-1&& testcase<=17 && testcase!=6 && testcase!=10)
			{
			{
			//pid_handle(0,0,1000,95,110,0);
			a=GPIO_ReadPin(GPIOA,5);
			b=GPIO_ReadPin(GPIOA,6);
			if(a==0 && b==0 && flag2==1)
				{
				    prior2=0;
					prior=0;
					prior1=0;
					flag2=0;
					flag3=0;
					//intergral3=0;intergral2=0;
				}
			}
			//prior2=0;
			}
		}
		}
		}
	}

}
int main(void)
{
    /* Loop forever */




     *((__vo uint32_t*)0x40023C00)&=~(0x0f);
	*((__vo uint32_t*)0x40023C00)|=(0x02);
	//config clock cho usb fs
	RCC->CR|=1<<16;
	while(!(RCC->CR&(1<<17)));
	RCC->PLLCFGR|=1<<22;
	RCC->PLLCFGR&=~(0x3ff);// m
	RCC->PLLCFGR|=25;

	RCC->PLLCFGR&=~(0x1ff<<6);// multi n
	RCC->PLLCFGR|=(192<<6);
	//divide q
	RCC->PLLCFGR&=~(0x0f<<24);
	RCC->PLLCFGR|=(4<<24);//48mhz for otg fs
	//divide p
	RCC->PLLCFGR&=~(0x3<<16);
	RCC->PLLCFGR|=(0x01<<16);//48mhz for sys clock

	RCC->CR|=1<<24;
	while(!(RCC->CR&(1<<25)));

	RCC->CFGR&=~(0x03);
	RCC->CFGR|=0x02;
	while(((RCC->CFGR>>2)&0x03)!=0x02);
	RCC->CFGR&=~(0x0f<<4);
	RCC->CFGR|=0x08<<4;//ahb bus =24mhz
	////////////////////////////////////////////////////////////////////////////////

	GPIO_Handle_t x;

	tim1.timx=TIM1;
	tim1.timy.mode=0;
	tim1.timy.ARR_control=TIM_ARR_DI;
	tim1.timy.DIR_control=TIM_UPCNT;
	tim1.timy.one_pulse=TIM_ONE_PULSE_DI;
	tim1.timy.psc=23; //1us
	TIM_Init(&tim1);
	//GPIO_Handle_t y;
		x.gpiox=GPIOC;
		x.gpioy.mode= GPIO_INPUT;
		x.gpioy.optype=GPIO_OUTPUT_PP;
		x.gpioy.speed=GPIO_VR_HIGH_SPEED;
		x.gpioy.gpio_pin=GPIO_PIN_13;
		//x.gpioy.alt_num=GPIO_PIN_AF0;
		x.gpioy.pupd=GPIO_PU;
		GPIO_Init(&x);
		NVIC_IRQ_ConFig(25,ENABLE);
		NVIC_IRQ_PriorityConFig(25,1);


		TIM1->DIER|=1;

		TIM1->CR1|=1;
		line_init();
		encoder_init();
		sonic_init();
		TIM2_init();
		TIM2_PWM();

/////////////////////////////////////---line---////////////////////////////////


  	while(1)
	{

	}
}
void OTG_FS_IRQHandler()
  {
	OTG_IRQ_Handle(&g);
  }
void TIM1_UP_TIM10_IRQHandler ()
 {
	//dọc line 1ms
	if(testcase!=5 && testcase<15) flag1=0;
	dem1++;	dem4++;
	if(dem1>=20)
	{
	data_left=read_data_line();
	if(data_left1!=7 && data_left==7)
	{
		 intergral3=0;intergral2=0;
	}
	if(data_left!=7) data_left_last=data_left;
	data_left1=data_left;
	dem1=0;
	}
	//chon mode
	if(GPIO_ReadPin(GPIOB,GPIO_PIN_4)==1) modem=1;
	else modem=0;
	if(GPIO_ReadPin(GPIOC,GPIO_PIN_13)==1) colo='r';else colo='b';
	//sys_handle(modem,'b');
	dem++;
	//bat sonic
	if((testcase==3 || testcase==4 ||testcase>=17) && flag==0)
	{
	GPIO_WritePin(GPIOA,GPIO_PIN_9,SET);
	GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
	if(dem3>=65000) dem3=0;
	dem3++;
	}
	if(dem4>=1000)
	{
		count_left=en_left;
		//if(testcase<=15)
		 en_left=0;
		 count_right=en_right;
		// if(testcase<=15)
		 en_right=0;

		sys_handle(modem,colo);
		dem4=0;
	}
	TIM_IRQ_Handle(&tim1);
 }
void EXTI9_5_IRQHandler()
{
	a=GPIO_ReadPin(GPIOA,5);
	b=GPIO_ReadPin(GPIOA,6);
	c=GPIO_ReadPin(GPIOA,8);
	//d=GPIO_ReadPin(GPIOA,9);
	//if(testcase<17)
	{
	if(testcase!=1)
	{
    if(a==1 && b==0 &&flag1==0)
	{

		if(prior==0 && prior1==0 && prior2==0)
		{

			prior=1;
			//if((GPIO_ReadPin(GPIOA,GPIO_PIN_0)==1 )||(GPIO_ReadPin(GPIOA,GPIO_PIN_4)==1)) prior1=1;
			testcase++;

			flag3=1;
		}

	}
    else if(b==1 && a==0&& flag1==0)
    {

    		if(prior==0 && prior1==0 && prior2==0)
    		{

    			prior=1;
    			//if((GPIO_ReadPin(GPIOA,GPIO_PIN_0)==1 )||(GPIO_ReadPin(GPIOA,GPIO_PIN_4)==1)) prior1=1;
    			testcase++;
    			flag3=2;
    		}

    }
	}
	else
	{
	    if(a==1 && b==0 &&flag1==0 && colo=='r')
		{
			if(prior==0 && prior1==0 && prior2==0)
			{

				prior=0;
				testcase=1;
				flag3=1;
			}

		}
	    else if (b==1 && a==0 &&flag1==0 && colo=='r')
	    {
			if(prior==0 && prior1==0 && prior2==0)
			{

				prior=1;
				testcase++;
				flag3=1;
			}
	    }
	    if(b==1 && a==0 &&flag1==0 && colo=='b')
		{
			if(prior==0 && prior1==0 && prior2==0)
			{

				prior=0;
				testcase=1;
				flag3=1;
			}

		}
	    else if (a==1 && b==0 &&flag1==0 && colo=='b')
	    {
			if(prior==0 && prior1==0 && prior2==0)
			{

				prior=1;
				testcase++;
				flag3=1;
			}
	    }
	}
	}
    if(c==1)
    {
    	d=dem3;
    	dem3=0;
    }
  	GPIO_IRQ_Handling(GPIO_PIN_5);
  	GPIO_IRQ_Handling(GPIO_PIN_6);
  	GPIO_IRQ_Handling(GPIO_PIN_8);
  	//GPIO_IRQ_Handling(GPIO_PIN_9);
}
void EXTI15_10_IRQHandler ()
{
	  if(EXTI->PR&(1<<12) ||EXTI->PR&(1<<11) )
	  {
			uint8_t a1=GPIO_ReadPin(GPIOB,GPIO_PIN_12);
			uint8_t b1=GPIO_ReadPin(GPIOA,GPIO_PIN_11);
	if((a1==1)!=(b1==1))
	{
		en_left++;
		en1_left++;
	}
	    else
	    	{
	    	  en_left--;
	    	  en1_left--;
	    	}
	  EXTI->PR|=(1<<12)|(1<<11);
	  }

	  else  if(EXTI->PR&(1<<10) ||EXTI->PR&(1<<15) )
	  {
			uint8_t a2=GPIO_ReadPin(GPIOB,GPIO_PIN_15);
			uint8_t b2=GPIO_ReadPin(GPIOA,GPIO_PIN_10);
	if((a2==1)!=(b2==1))
	{
 		en_right++;
		en1_right++;
	}
	    else
	    	{
	    	  en_right--;
 	    	  en1_right--;
	    	}
	  EXTI->PR|=(1<<10)|(1<<15);
	  }

     }
void EXTI0_IRQHandler ()
{
	if(GPIO_ReadPin(GPIOA,GPIO_PIN_0)==1 && prior==1)
		{
		  prior1=1;
		  intergral3=0;intergral2=0;
		  control_case(testcase,colo);
		  sys_handle(modem,colo);
		  //control_case(testcase,colo);
		}
	GPIO_IRQ_Handling(GPIO_PIN_0);
 }
void EXTI4_IRQHandler()
{
	if(GPIO_ReadPin(GPIOA,GPIO_PIN_4)==1 && prior==1)
		{
		 prior1=1;
		 intergral3=0;intergral2=0;
 		 control_case(testcase,colo);
		 sys_handle(modem,colo);
		 //control_case(testcase,colo);
		}
	GPIO_IRQ_Handling(GPIO_PIN_4);
 }
